# Generated by Django 3.1.3 on 2020-11-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='title of the article')),
                ('body', models.TextField(verbose_name='Body of the article')),
                ('featured_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Blog article',
                'verbose_name_plural': 'Blog articles',
            },
        ),
    ]
